//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int id { get; set; }
        public string client { get; set; }
        public string product { get; set; }
        public int amount { get; set; }
        public double price { get; set; }
        public System.DateTime date { get; set; }
        public bool orderShipped { get; set; }
    }
}
