//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Folder
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string FolderName { get; set; }
        public long ForumId { get; set; }
        public string image { get; set; }
    }
}
